---
version: '3'
services:
  invoicer:
    image: "rflathers/invoicer:${CIRCLE_SHA1:0:7}"
    build:
      context: .
      dockerfile: Dockerfile

  zap:
    image: owasp/zap2docker-weekly
    depends_on:
      - invoicer