version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:latest

    working_directory: /go/src/github.com/ropnop/invoicer
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Testing Application
          command: go test /go/src/github.com/ropnop/invoicer

      - run:
          name: Build Application
          command: go build --ldflags '-extldflags "-static"' .

      - run:
          name: Build Docker
          command: |
            docker build -t rflathers/invoicer:${CIRCLE_SHA1:0:7} .