version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:latest

    working_directory: /go/src/github.com/ropnop/invoicer
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Testing Application
          command: go test /go/src/github.com/ropnop/invoicer

      - run:
          name: Build Application
          command: |
            go build --ldflags '-extldflags "-static"' .
            docker-compose -p ${CIRCLE_SHA1:0:7} build invoicer

      - run:
          name: OWASP ZAP Checks
          # Only fail on error code 1, which indicates at least one FAIL was found.
          # error codes 2 & 3 indicate WARN or other, and should not break the run
          command: |
            (
            docker-compose -p ${CIRCLE_SHA1:0:7} run zap zap-baseline.py \
              -t http://invoicer:8080/ || \
            if [ $? -ne 1 ]; then exit 0; else exit 1; fi;
            )

      - deploy:
          command: |
            if [[ "${CIRCLE_BRANCH}" == "master" ]]; then
              docker-compose -p ${CIRCLE_SHA1:0:7} push invoicer
            fi