version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:latest

    working_directory: /go/src/github.com/ropnop/invoicer
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Testing Application
          command: go test /go/src/github.com/ropnop/invoicer

      - run:
          name: Build Application
          command: |
            go build --ldflags '-extldflags "-static"' .
            docker build -t rflathers/myinvoicer:${CIRCLE_SHA1:0:7} .

      - run:
          name: Run App in Background
          command: docker run rflathers/myinvoicer:${CIRCLE_SHA1:0:7}
          background: true

      - run:
          name: OWASP ZAP Checks
          command: |
            docker pull owasp/zap2docker-weekly
            docker run -t owasp/zap2docker-weekly zap-baseline.py -t http://172.17.0.2:8080/ || \
            if [ $? -ne 1 ]; then exit 0; else exit 1; fi

      - deploy:
          command: |
            if [[ "${CIRCLE_BRANCH}" == "master" ]]; then
              docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
              docker push rflathers/myinvoicer:${CIRCLE_SHA1:0:7}
            fi