version: 2
jobs:
  Test and Build:
    docker:
      - image: circleci/golang:latest

    working_directory: /go/src/github.com/ropnop/invoicer
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Testing Application
          command: go test /go/src/github.com/ropnop/invoicer

      - run:
          name: Build Application
          command: docker build -t rflathers/myinvoicer:${CIRCLE_SHA1:0:7} .
  
  Push and Deploy:
    docker:
      - image: circleci/golang:latest

    steps:
      - setup_remote_docker

      - deploy:
          command: |
            if [[ "${CIRCLE_BRANCH}" == "master" ]]; then
              docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
              docker push rflathers/myinvoicer:${CIRCLE_SHA1:0:7}
            fi

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build