version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:latest

    working_directory: /go/src/github.com/ropnop/invoicer
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Testing Application
          command: go test /go/src/github.com/ropnop/invoicer

      - run:
          name: Build Application
          command: go build --ldflags '-extldflags "-static"' .

      - deploy:
          command: |
            if [[ "${CIRCLE_BRANCH}" == "master" ]]; then
              docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
              docker build -t rflathers/invoicer:${CIRCLE_SHA1:0:7} .
              docker push rflathers/invoicer:${CIRCLE_SHA1:0.7}
            fi